import Navbar from '@/components/Navbar';
import Providers from '@/lib/providers/Providers';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className="page-bg">
          <header>
            <nav>
              <Navbar />
            </nav>
          </header>
          <main className="h-screen">{children}</main>
        </body>
      </html>
    </Providers>
  );
}
